apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-controller
  namespace: self-healing
  labels:
    app: aiops-controller

spec:
  replicas: 1

  selector:
    matchLabels:
      app: aiops-controller

  template:
    metadata:
      labels:
        app: aiops-controller

    spec:
      serviceAccountName: aiops-controller

      containers:
        - name: aiops
          image: self-healing-aiops:v18
          imagePullPolicy: IfNotPresent

          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus-kube-prometheus-prometheus.monitoring:9090"

            - name: AIOPS_DRY_RUN
              value: "true"

            - name: ARGOCD_NAMESPACE
              value: "argocd"

            - name: ARGOCD_APPLICATION
              value: "self-healing"

            - name: ARGOCD_SOURCE_BRANCH
              value: "test/broken-release"

            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aiops-github
                  key: GITHUB_TOKEN

            - name: GITHUB_REPOSITORY
              value: "cloudwithnikhil/autonomous-self-healing-k8s"

            - name: GITHUB_WORKFLOW
              value: "aiops-remediation.yml"

            - name: GITHUB_WORKFLOW_TIMEOUT_SECONDS
              value: "180"

            - name: GITHUB_WORKFLOW_POLL_SECONDS
              value: "5"

            - name: GITHUB_BRANCH_ADVANCE_TIMEOUT_SECONDS
              value: "120"

            - name: RECOVERY_TIMEOUT_SECONDS
              value: "600"

            - name: RECOVERY_POLL_SECONDS
              value: "10"

            - name: RECOVERY_ERROR_RATE_THRESHOLD
              value: "0.05"

          ports:
            - name: http
              containerPort: 8001

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
