apiVersion: v1
kind: Service
metadata:
  name: aiops-controller
  namespace: self-healing
  labels:
    app: aiops-controller
spec:
  selector:
    app: aiops-controller

  ports:
    - name: http
      port: 8001
      targetPort: 8001

  type: ClusterIP